---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    datacenter_name: 'hcm-dc65-01'
    cluster_name: 'hcm-cluster01'
    vcenter_hostname: '172.29.40.19'
    vcenter_password: 'R@ckware4IT'
    vcenter_username: 'administrator@vsphere.local'
    name: 'tf-centos65x64'
    folder: '/Suresh Pawar/'

  tasks:
  - name: Set the state of a virtual machine to poweroff
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      folder: "{{ folder }}"
      name: "{{ name }}"
      state: poweredoff

  - name: Create a clean os snapshot
    vmware_guest_snapshot:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      validate_certs: False
      folder: "{{ folder }}"
      name: "{{ name }}"
      state: present
      snapshot_name: Clean_OS
      description: clean os snapshot
    delegate_to: localhost

  - name: Power On the virtual machine
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter_name }}"
      validate_certs: no
      folder: "{{ folder }}"
      name: "{{ name }}"
      state: poweredon
    delegate_to: localhost

